### ISSUE TITLE
speculative meshes on minnie

### ISSUE THREAD

**Issue by fcollman** [seung-lab/PyChunkedGraph#232]
something in #228  or #229 broke the way that speculative meshes are working on the latest branch minnie

I think i've traced it down to the fact that now we are passing level, which is the level of the node_id by default

Before this line was setting that level = 6 for the speculative manifests.  I don't know if level=6 is actually available somewhere in metadata.  I can have cloud-volume pass in level=6.. but that feels long term wrong.

https://github.com/seung-lab/PyChunkedGraph/blob/akhilesh-unit-tests/pychunkedgraph/meshing/manifest.py#L277

**Comment by akhileshh** [comment]
not sure I understand the issue completely, is this regarding minnie dataset?
[This](https://github.com/seung-lab/PyChunkedGraph/blob/2c1c28f03d3bb60b8b08df214d6d81d7f37dffe0/pychunkedgraph/meshing/manifest.py#L306) can be used as `start_layer`
`MAX_STITCH_LAYER` is set right after ingest process, I think it is 7 for minnie and 4 for pinky

I do agree that setting it to 6 [here](https://github.com/seung-lab/PyChunkedGraph/blob/2c1c28f03d3bb60b8b08df214d6d81d7f37dffe0/pychunkedgraph/meshing/manifest.py#L277) is not standard, that was leftover when we were initially figuring out how high should stitching go for minnie.

**Comment by fcollman** [comment]
yes.. this is regarding minnie.

The problem is that in order to have speculative meshes work with bounding boxes, I changed the code to pass the start_layer down through the speculative manifest call chain.. but start_layer was getting set equal to the node_id's value, which was wrong.  So the code that had it default to MAX_STITCH_LAYER i think needed to be brought farther up the call stack.

**Comment by akhileshh** [comment]
In that case maybe it is better to not make `start_layer` an optional parameter, the function does not really need to assume an arbitrary start layer
I'm working on refactoring manifest code and add clear documentation for fragment ID formats, will make this change as well

**Comment by fcollman** [comment]
this is being addressed by #234
