### ISSUE TITLE
HTTP endpoint for accessing ids involved in a set of operations

### ISSUE THREAD

**Issue by nicholasturner1** [seung-lab/PyChunkedGraph#249]
An HTTP endpoint exists for accessing operation ids from the changelog for particular segment root ids.

https://github.com/seung-lab/PyChunkedGraph/blob/729ccb1be066b2d0d736ba81cba6a2d7207306f8/pychunkedgraph/app/segmentation/v1/routes.py#L256

However, it's not currently possible to retrieve the segment root ids involved in each of the operation ids. This is important for anyone using this service to understand the changes in the log.

**Comment by akhileshh** [comment]
implemented in #261 , endpoint is `/table/<table_id>/operation_details?operation_ids=[1,2,3]`
