### ISSUE TITLE
Does handle_is_latest_roots do anything with the timestamp?

### ISSUE THREAD

**Issue by jefferis** [seung-lab/PyChunkedGraph#265]
@sdorkenw @fcollman I get the impression that the `timestamp` part may have been boiler plate as I can't see that it is used. Was the intention to add a time limit to the [read_node_id_rows](https://github.com/seung-lab/PyChunkedGraph/blob/8e09144a60e829b6f6d1f147553b6e0a24dcf814/pychunkedgraph/backend/chunkedgraph.py#L1039) call?

https://github.com/seung-lab/PyChunkedGraph/blob/c485eb2af676ee3c360d975d5cc9684b25f43870/pychunkedgraph/app/segmentation/common.py#L1103-L1120

**Comment by sdorkenw** [comment]
Indeed, this is not used. I will add it now to the `read_node_id_rows` call. This will effectively declare root ids as latest when there has not been an edit to this root id before the provided timestamp.
