### ISSUE TITLE
find_path with precision mode error in minnie

### ISSUE THREAD

**Issue by fcollman** [seung-lab/PyChunkedGraph#296]
```{"message": "module 'pychunkedgraph.meshing.meshgen' has no attribute 'get_missing_initial_meshes'", "user_id": "10.244.4.5", "user_ip": "10.244.4.5", "request_time": "2021-04-16T16:55:38.702315", "request_url": "https://minnie.microns-daf.com/segmentation/api/v1/table/minnie3_v1/graph/find_path?precision_mode=True", "request_data": "b'[[864691135776832352, 974780, 785252, 794760], [864691135776832352, 962132, 838284, 808360]]'", "response_time": 2680.8371543884277, "response_code": 500, "traceback": ["Traceback (most recent call last):\n", "  File \"/usr/local/lib/python3.7/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n    rv = self.dispatch_request()\n", "  File \"/usr/local/lib/python3.7/site-packages/flask/app.py\", line 1936, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n", "  File \"/usr/local/lib/python3.7/site-packages/middle_auth_client/decorators.py\", line 106, in decorated_function\n    return f(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.7/site-packages/middle_auth_client/decorators.py\", line 254, in decorated_function\n    return f(*args, **kwargs)\n", "  File \"./pychunkedgraph/app/segmentation/v1/routes.py\", line 374, in find_path\n    find_path_result = common.handle_find_path(table_id, precision_mode)\n", "  File \"./pychunkedgraph/app/segmentation/common.py\", line 1078, in handle_find_path\n    centroids, failed_l2_ids = mesh_analysis.compute_mesh_centroids_of_l2_ids(cg, l2_path, flatten=True)\n", "  File \"./pychunkedgraph/meshing/mesh_analysis.py\", line 83, in compute_mesh_centroids_of_l2_ids\n    fragment_map = meshgen.get_missing_initial_meshes(cv, files_contents)\n", "AttributeError: module 'pychunkedgraph.meshing.meshgen' has no attribute 'get_missing_initial_meshes'\n"], "time": "2021-04-16T16:55:41.0Z", "severity": "ERROR", "source": "pychunkedgraph.app"}```

Got this error trying to use the find path endpoint.

**Comment by manuel-castro** [comment]
I removed that function in the meshgen module and forgot that it was being used here. I'll fix this.

**Comment by fcollman** [comment]
this is fixed awhile ago
