### ISSUE TITLE
Refactor cloudvolume.storage.Storage into CloudFiles

### ISSUE THREAD

**Issue by william-silversmith** [seung-lab/PyChunkedGraph#449]
I've been trying to refactor CloudVolume to adjust how how it handles paths and the legacy Storage module is adding a bit of friction. I don't know where else Storage is used, but it's been deprecated for a long time and I'd like to remove it at some point. Would it be possible to switch calls to Storage to CloudFiles?

https://github.com/seung-lab/PyChunkedGraph/blob/4e5b2b2b095511527992eabf44cbcc891eb3e5b1/pychunkedgraph/meshing/manifest/__init__.py#L56

**Comment by akhileshh** [comment]
I think we removed all but this. Will do. Not sure how this was missed.
Also the calling function doesn't seem to be used anywhere.
