### ISSUE TITLE
Don't use random labels for new nodes

### ISSUE THREAD

**Issue by nkemnitz** [seung-lab/PyChunkedGraph#6]
Whenever a merge/split is performed and new nodes need to be generated, we are currently generating random IDs until we hit one that is not yet in use. This is bad because:
- it makes the system less predictable / tests harder
- performance will suffer once we have a chunk with many nodes and
- the graph will eventually get stuck without throwing an error.

Can't we store the next free ID in a chunk row, or even a local hash table?
For a dataset with 250,000 x 250,000 x 25,000 voxel and a chunksize of 512 x 512 x 64 voxel, that's 93,496,311 chunks on the base layer. 8 Byte per chunks is ~750MB

**Comment by sdorkenw** [comment]
This requires atomic readwrite requests which we do not have right now but should at some point. However, it should only start to matter when we scale beyond pinky as there are currently >10^9 possible ids for a maximum of ~10^6 actual ids on the highest layer. Hence, there is a 0.001 chance that a random id already exists.

In my opinion, the more important problem is that the risk of collisions goes up with larger datasets.

**Comment by sdorkenw** [comment]
Fixed in `21d1b20`.
IDs are now chosen consecutively. `find_next_node_id` uses a atomic counter - one for each chunk. However, this increases the numbers of reads and writes for splits and merges.
