### ISSUE TITLE
Use read_row for all row reads

### ISSUE THREAD

**Issue by sdorkenw** [seung-lab/PyChunkedGraph#76]
`read_row(...)` provides fail safety that is needed to catch cases where rows do not exist or do not contain the desired `family_ids` and / or `keys`. Not all row reads use this function because it does not provide a generic enough interface for all requests. We should male `read_row` more generic and adapt all `self.table.read_row(...)` commands.

**Comment by nkemnitz** [comment]
Think that got resolved during https://github.com/seung-lab/PyChunkedGraph/pull/112 - all row reads now use the same core function for reading pre-defined columns. Anything missing?
