### ISSUE TITLE
Id space in upper layers is currently to small for very large datasets

### ISSUE THREAD

**Issue by sdorkenw** [seung-lab/PyChunkedGraph#9]
We will not have enough ids in our 32bit unique node id part to assign ids to all root segments in very large datasets (like phase 2). At the same time, only a small number of chunks (1, 8, 64, ...) are encoded in the second 32bits (-4bits for the layer). We should limit the chunk part to 16bit for the highest layers and repurpose the 16bit to be able to assign 48bit ids to abstract nodes.

**Comment by nkemnitz** [comment]
Similar issue for the Chunk IDs on the leaf layer of large datasets:
The last aligned version of Basil was 232,426 x 280,917 x 999 voxel large. With the current chunk size of 512x512x64, we would need 9 Bit / 10 Bit to address all chunks in x and y dimension, but currently hard-coded 8 Bit for each dimension.

For Basil, which only has 1000 slices, we might get away by adjusting the chunk size to 2048x2048x8 (2x larger). That won't work for larger datasets.

Think we might need a special bitmask for every layer of the Chunked Graph -- if we want to keep the Neuroglancer-compatible 64 bit Labels.

**Comment by sdorkenw** [comment]
Fixed in `21d1b20`.
The chunk ids now cover 8 bytes for the latyer id +  as many bits for dimension as needed (at least one). The atomic layer is currently exempt (4 x 8 bytes) from that due to the statically generated files. This can be changed in the futures.
